<?php

// DO NOT EDIT THIS FILE... WHEN MARKING, I WILL
// BE USING MY OWN VERSION OF IT, NOT YOURS

unset($_REQUEST);
unset($_POST);
unset($_GET);
unset($_COOKIE);

$_POST = array(
  'first_name' => 'Tom',
  'last_name' => 'Jones',
  'email' => 'tom@hotmail.com'
);

$_GET = array(
  'first_name' => 'Bill',
  'last_name' => 'Franks',
  'email' => 'bill@gmail.com'
);

$_COOKIE = array(
  'first_name' => 'Reggie',
  'last_name' => 'Banister',
  'email' => 'reggie@yahoo.com'
);

$_REQUEST = array(
  'first_name' => 'Beanie',
  'last_name' => 'McDoodle',
  'email' => 'beanie@yahoo.com'
);

require __DIR__ . '/../Lib/Input.php';



?>
<h1>Lab 4 Test File</h1>

<h2>$_REQUEST full</h2>

<pre>
  <?php var_dump(Input::request()); ?>
</pre>

<h2>$_REQUEST fields</h1>

  <pre>
<?php var_dump(Input::request('first_name')); ?>
<?php var_dump(Input::request('city')); ?>
</pre>

  <hr />

  <h2>$_POST full</h2>

  <pre>
  <?php var_dump(Input::post()); ?>
</pre>

  <h2>$_POST fields</h1>

    <pre>
<?php var_dump(Input::post('first_name')); ?>
<?php var_dump(Input::post('city')); ?>
</pre>

    <hr />

    <h2>$_GET full</h2>

    <pre>
  <?php var_dump(Input::get()); ?>
</pre>

    <h2>$_GET fields</h1>

      <pre>
<?php var_dump(Input::get('first_name')); ?>
<?php var_dump(Input::get('city')); ?>
</pre>

      <hr />

      <h2>$_COOKIE full</h2>

      <pre>
  <?php var_dump(Input::cookie()); ?>
</pre>

      <h2>$_COOKIE fields</h1>

        <pre>
<?php var_dump(Input::cookie('first_name')); ?>
<?php var_dump(Input::cookie('city')); ?>
</pre>

        <hr />

        <h1>END</h1>